# Generated by Django 3.2.16 on 2022-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cars')),
                ('name', models.CharField(max_length=212)),
                ('stars', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('transmission', models.IntegerField(choices=[(0, 'Mechanic'), (1, 'Auto'), (2, 'AI')], default=1)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
