# Generated by Django 3.2.16 on 2022-10-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyf', models.CharField(max_length=212)),
                ('wyg', models.CharField(max_length=212)),
                ('jurney_d', models.DateTimeField(auto_now_add=True)),
                ('return_d', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
