# Generated by Django 3.2.16 on 2022-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='jurney_d',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_d',
            field=models.DateField(),
        ),
    ]
