# Generated by Django 3.2.16 on 2022-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='how_it_works',
            name='hiw_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
